import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LenisProvider from "../components/LenisProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const abcDiatype = localFont({
  src: [
    { path: "../public/ABC Diatype Thin.ttf", weight: "200", style: "normal" },
    { path: "../public/ABCLight.woff2", weight: "300", style: "normal" },
    { path: "../public/ABCLight.woff", weight: "300", style: "normal" },
    { path: "../public/ABCRegular.woff2", weight: "400", style: "normal" },
    { path: "../public/ABCRegular.woff", weight: "400", style: "normal" },
    { path: "../public/ABC Diatype Medium.ttf", weight: "500", style: "normal" },
  ],
  variable: "--font-abc-diatype",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={abcDiatype.variable}>
      <body className={abcDiatype.className}>
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  );
}
