name: Build and push staging images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { name: gateway, path: services/gateway-api, image: cav-gateway }
          - { name: webhooks, path: services/webhooks, image: cav-webhooks }
          - { name: chat, path: services/chat-service, image: cav-chat }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.service.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.path }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service.image }}:staging
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service.image }}:staging-${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ matrix.service.image }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ matrix.service.image }}:buildcache,mode=max
